version: '3.7'

services:
  bot:
    build:
      context: ./src/bot
      dockerfile: bot.dockerfile
    restart: on-failure
    environment:
      REDIS_HOST: redis
      POSTGRES_SERVER: db
    volumes:
      - ./logs:/bot/logs
      - ./locales:/bot/locales
      - ./data/files:/bot/files
    env_file:
      - .env
    depends_on:
      - db
  web:
    build:
      context: ./src/web
      dockerfile: web.dockerfile
    ports:
      - "7777:8000"
    restart: on-failure
    volumes:
      - ./src/web:/web
    env_file:
      - .env
    command: >
      sh -c "sleep 10 &&
             poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: on-failure
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  pgadmin:
    image: dpage/pgadmin4:6.0
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test